dist: bionic

# The following enables several GHC versions to be tested; often it's enough to
# test only against the last release in a major GHC version. Feel free to omit
# lines listings versions you don't need/want testing for.
env:
  - CABALVER=2.4 GHCVER=7.6.3
  - CABALVER=2.4 GHCVER=7.8.4
  - CABALVER=2.4 GHCVER=7.10.3
  - CABALVER=2.4 GHCVER=8.0.2
  - CABALVER=2.4 GHCVER=8.2.2
  - CABALVER=2.4 GHCVER=8.4.4
  - CABALVER=2.4 GHCVER=8.6.5
  - CABALVER=2.4 GHCVER=8.8.3
  - CABALVER=2.4 GHCVER=8.10.1
# - CABALVER=head GHCVER=head   # see section about GHC HEAD snapshots

# Note: the distinction between `before_install` and `install` is not important.
before_install:
  # We remove the pgdg.list file because it's there to add the postgresql
  # repository, and we don't need it. Leaving it in causes problems with Ubuntu
  # Bionic (the distro is no longer supported by postgresql).
  - sudo rm /etc/apt/sources.list.d/pgdg.list

  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install --yes libcwiid-dev libsdl1.2-dev
  - travis_retry sudo apt-get install --yes cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - cabal --version
  - ghc --version
  - travis_retry cabal update

install:
  - travis_retry cabal install --enable-tests -fexamples --only-dependencies yampa/ yampa-test/

script:
  - if [ "${TRAVIS_HASKELL_VERSION}" == "8.4.4" ]; then cabal install -ftest-doc-coverage --run-tests -j1  yampa/ yampa-test/; else cabal install --enable-tests -fexamples -j1 yampa/ yampa-test/; fi

after_script:

branches:
    only:
          - master
          - /^develop.*$/
          - /^hotfix.*$/
          - /^release.*$/
